services:
  db:
    image: postgres:18-alpine
    container_name: soc-db
    environment:
      POSTGRES_USER: crru_user
      POSTGRES_PASSWORD: crru_password
      POSTGRES_DB: crru_social
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  academic_service:
    build:
      context: ./backend
      dockerfile: academic_service/Dockerfile
    container_name: soc-academic-service
    ports:
      - "18001:8001"
    environment:
      - DATABASE_URL=postgresql://crru_user:crru_password@db:5432/crru_social?options=-csearch_path=schema_academic
    depends_on:
      - db

  news_service:
    build:
      context: ./backend
      dockerfile: news_service/Dockerfile
    container_name: soc-news-service
    ports:
      - "18002:8002"
    environment:
      - DATABASE_URL=postgresql://crru_user:crru_password@db:5432/crru_social?options=-csearch_path=schema_news
    depends_on:
      - db

  research_service:
    build:
      context: ./backend
      dockerfile: research_service/Dockerfile
    container_name: soc-research-service
    ports:
      - "18003:8003"
    environment:
      - DATABASE_URL=postgresql://crru_user:crru_password@db:5432/crru_social?options=-csearch_path=schema_research
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: soc-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api/v1
    depends_on:
      - academic_service
      - news_service
      - research_service

  nginx:
    image: nginx:1.30.2-alpine
    container_name: soc-nginx-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - academic_service
      - news_service
      - research_service

volumes:
  pgdata:
